### ISSUE TITLE
项目中引入权限框架的几率有多大，可以考虑

### ISSUE THREAD

**Issue by zzpp515630** [ohnewfisher/troubling#14]
是否会增加项目复杂性

**Comment by runME** [comment]
1.  需求越多,项目肯定越复杂,更考验架构,把职责分清,模块解耦,代码弄清楚,但是对于复杂系统,一开始几乎是不可能考虑到所有的点,重构是必须的.那重构的基础是我们的测试要跟上.
2. 目前项目的状态不太可能引入权限框架,自己造轮子可能性更大
