### ISSUE TITLE
后端应该默认不相信前端的任何数据

### ISSUE THREAD

**Issue by tenywen** [ohnewfisher/troubling#17]
目前后端会大量依靠前端的数据来判断，服务器应该只需要前端关键的id等信息，其他都以服务器数据为准。

**Comment by runME** [comment]
话分两头说,如果都不相信,那后端的数据来自哪里,应该是加强安全措施,使的非法手段的实施成本更高,这世界永远没有不透风的墙,微信支付宝钉钉也不是绝对的安全,比如钉钉的考勤打卡,仍然有办法破解,只是成本问题.
所以,不能因噎废食

**Comment by runME** [comment]
另一方面,从软件发展角度来说,make it work -> make it right ->make it fast ->make it security 是一步步来的
